### ISSUE TITLE
Cors Eror

### ISSUE THREAD

**Issue by Satendra-singh-oos** [danishhansari/CRUD#1]
Your Client Side env should look like this:- VITE_SERVER="http://localhost:8080"
Yor Server Side env Should look like this  :- CORS_ORIGIN=http://localhost:5173
And move the app.use(
  cors({
    origin: process.env.CORS_ORIGIN,
    credentials: true,
  })
); in the app.js file 

also make sure you passing the {withCredentials: true,} in axios request

**Comment by danishhansari** [comment]
Thanks mate i applied all the changes and it works as i want. You effort is appreciated
